# Generated by Django 4.1.5 on 2023-01-27 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_app', '0006_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permission',
            options={'ordering': ('id',), 'verbose_name': 'Permission', 'verbose_name_plural': 'Permissions'},
        ),
        migrations.AlterModelOptions(
            name='rolepermission',
            options={'ordering': ('role_id', 'permission'), 'verbose_name': 'RolePermission', 'verbose_name_plural': 'RolePermissions'},
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='role', to='corporate_app.role'),
        ),
    ]
