# Generated by Django 4.1.5 on 2023-01-27 11:49

import corporate_app.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_app', '0009_alter_tasks_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='file',
            field=models.FileField(blank=True, upload_to='files/tasks/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'doc', 'docx', 'xlsx', 'pptx', 'pdf'])]),
        ),
        migrations.CreateModel(
            name='Folders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='corporate_app.folders')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('file', models.FileField(upload_to=corporate_app.models.file_upload_to, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'doc', 'docx', 'xlsx', 'pptx', 'pdf'])])),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporate_app.folders')),
            ],
        ),
    ]
