# Generated by Django 4.1.5 on 2023-01-27 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_app', '0011_alter_files_options_alter_folders_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='folder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corporate_app.folders'),
        ),
        migrations.AlterField(
            model_name='folders',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='corporate_app.folders'),
        ),
    ]
