# Generated by Django 4.1.5 on 2023-01-27 12:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_app', '0012_alter_files_folder_alter_folders_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='file',
            field=models.FileField(blank=True, upload_to='files/tasks', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'doc', 'docx', 'xlsx', 'pptx', 'pdf'])]),
        ),
    ]
