# Generated by Django 4.1.5 on 2023-02-01 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_app', '0014_message_lastmessagesusers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat_files', verbose_name='File'),
        ),
    ]
