# Generated by Django 4.1.5 on 2023-02-01 10:53

import corporate_app.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_app', '0015_alter_message_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='images/avatars/person.png', upload_to='images/avatars', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg']), corporate_app.models.validate_file_size], verbose_name='Picture'),
        ),
    ]
