# Generated by Django 4.1.5 on 2023-02-04 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_app', '0016_alter_user_avatar'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LastMessagesUsers',
            new_name='Dialog',
        ),
    ]
