# Generated by Django 4.1.5 on 2023-02-04 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corporate_app', '0017_rename_lastmessagesusers_dialog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dialog',
            options={'ordering': ('edited',)},
        ),
        migrations.AddField(
            model_name='dialog',
            name='edited',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
